[
	{
		firstName: "Hiruzen",
		lastName: "Sarutobi",
		phoneNumber: "123456789",
		email: "HiruzenSarutobi@test.com",
		role: "Admin",
	},
	{
		firstName: "Kakashi",
		lastName: "Hatake",
		phoneNumber: "123456789",
		email: "KakashiHatake@test.com",
		role: "Project Manager",
	},
	{
		firstName: "Naruto",
		lastName: "Uzumaki",
		phoneNumber: "123456789",
		email: "NarutoUzumaki@test.com",
		role: "Employee",
	},
	{
		firstName: "Sasuke",
		lastName: "Uchiha",
		phoneNumber: "123456789",
		email: "SasukeUchiha@test.com",
		role: "Employee",
	},
	{
		firstName: "Sakura",
		lastName: "Haruno",
		phoneNumber: "123456789",
		email: "SakuraHaruno@test.com",
		role: "Employee",
	},
	{
		firstName: "Asuma",
		lastName: "Sarutobi",
		phoneNumber: "123456789",
		email: "AsumaSarutobi@test.com",
		role: "Project Manager",
	},
	{
		firstName: "Shikamaru",
		lastName: "Nara",
		phoneNumber: "123456789",
		email: "ShikamaruNara@test.com",
		role: "Employee",
	},
	{
		firstName: "Ino",
		lastName: "Yamanaka",
		phoneNumber: "123456789",
		email: "InoYamanaka@test.com",
		role: "Employee",
	},
	{
		firstName: "Choji",
		lastName: "Akimichi",
		phoneNumber: "123456789",
		email: "ChojiAkimichi@test.com",
		role: "Employee",
	},
];
